#!/usr/bin/env python3
# data/ の完全版ダッシュボードを単一ファイル化→gzip→src/web_ui_gz.h を再生成。
# UI(data/) を編集したら: python3 scripts/build_webui.py
import gzip, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "data")
def read(n): return open(os.path.join(D, n), encoding="utf-8").read()

html = read("index.html"); css = read("styles.css")
dummy = read("dummy-history.js"); app = read("app.js"); live = read("aqua-live.js")

html = html.replace('<link rel="stylesheet" href="styles.css">', "<style>\n"+css+"\n</style>")
for tag in ['<script src="dummy-history.js"></script>',
            '<script src="app.js" defer></script>',
            '<script src="aqua-live.js" defer></script>']:
    if tag not in html: sys.exit("missing tag: "+tag)
    html = html.replace(tag, "")
bundle = "<script>\n"+dummy+"\n</script>\n<script>\n"+app+"\n</script>\n<script>\n"+live+"\n</script>\n"
html = html.replace("</body>", bundle+"</body>")

raw = html.encode("utf-8")
gz = gzip.compress(raw, 9)
out = ["// AUTO-GENERATED by scripts/build_webui.py — do not edit by hand.",
       "// 完全版ダッシュボード(gzip)。LittleFS に index.html が無いとき配信。",
       "#pragma once", "#include <Arduino.h>", "",
       f"static const unsigned WEBUI_GZ_LEN = {len(gz)};",
       "static const uint8_t WEBUI_GZ[] PROGMEM = {"]
line = []
for b in gz:
    line.append(f"0x{b:02x},")
    if len(line) == 20: out.append("  "+"".join(line)); line = []
if line: out.append("  "+"".join(line))
out.append("};")
open(os.path.join(ROOT, "src", "web_ui_gz.h"), "w", encoding="utf-8").write("\n".join(out)+"\n")
print(f"src/web_ui_gz.h updated: raw {len(raw)} -> gzip {len(gz)} bytes")
